#!/bin/sh

import git:install/download.sh
import git:install/extract.sh

which ollama > /dev/null 2>&1 || {
    _download https://ollama.ai/download/Ollama-darwin.zip

    ollama_contents=$(mktemp -d)
    _extract $_DOWNLOADED_FILE $ollama_contents

    _sudo mv $ollama_contents/Ollama.app /Applications
    _sudo chmod +x /Applications/Ollama.app/Contents/Resources/ollama

    _sudo ln -s /Applications/Ollama.app/Contents/Resources/ollama $_CONF_INSTALL_BIN_PATH/ollama

    rm -rf $ollama_contents
}
